GET http://localhost:3000/products

###

POST http://localhost:3000/products Content-Type: application/json

{
    "name": "Stormtrooper",
    "type": "T-shirt",
    "price": "250",
    "id": "1234567"
}

###
DELETE http://localhost:3000/product/1234568

###

PUT http://localhost:3000/product/1234569

{
    "name": "Baby Yoda",
    "type": "Sweater",
    "price": "500",
    "id": "1234569"
}